# -*- coding: utf-8 -*-
"""BrainyBeam Info-Tech Pvt Ltd(Task_2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCTtLUS0bjxaNYND7qQy6vzvLF71WjYT

**Title: Multi-Data Series Violin Plot, Description:Create a violin plot with multiple data series.**
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

np.random.seed(10)
data = pd.DataFrame({
    'Series1': np.random.normal(0, 1, 100),
    'Series2': np.random.normal(5, 2, 100),
    'Series3': np.random.normal(-2, 3, 100)
})

data_melted = data.melt(var_name='Series', value_name='Values')

sns.violinplot(x='Series', y='Values', data=data_melted)
plt.show()